QLKS/Areas/Admin/Controllers/DichVuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS.Models;

namespace QLKS.Areas.Admin.Controllers
{
    public class DichVuController : Controller
    {
        private dataQLKSEntities db = new dataQLKSEntities();

        
        public ActionResult Index()
        {
            return View(db.tblDichVus.ToList());
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDichVu tblDichVu = db.tblDichVus.Find(id);
            if (tblDichVu == null)
            {
                return HttpNotFound();
            }
            return View(tblDichVu);
        }

        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file, [Bind(Include = "ma_dv,ten_dv,gia,don_vi,ton_kho")] tblDichVu tblDichVu)
        {
            if (ModelState.IsValid)
            {
                String anh = "/Content/Images/DichVu/default.png";
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);//Trả về tên tệp và phần mở rộng của chuỗi đường dẫn đã chỉ định.
                    String path = System.IO.Path.Combine(
                                           Server.MapPath("~/Content/Images/DichVu"), pic);//Kết hợp hai chuỗi thành một đường dẫn.
                    // file is uploaded
                    file.SaveAs(path);
                    anh = "/Content/Images/DichVu/" + pic;
                    // lưu đường dẫn hình ảnh vào cơ sở dữ liệu 
                    // trực tiếp vào cơ sở dữ liệu trong trường hợp nếu bạn muốn lưu trữ byte[]
                    
                    using (MemoryStream ms = new MemoryStream())//Tạo một luồng có kho lưu trữ dự phòng là bộ nhớ.
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }

                tblDichVu.anh = anh;
                db.tblDichVus.Add(tblDichVu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblDichVu);
        }

        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDichVu tblDichVu = db.tblDichVus.Find(id);
            if (tblDichVu == null)
            {
                return HttpNotFound();
            }
            return View(tblDichVu);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]//ngăn chặn các giả mạo yêu cầu trang web chéo
        public ActionResult Edit(HttpPostedFileBase file, [Bind(Include = "ma_dv,ten_dv,gia,don_vi,ton_kho")] tblDichVu tblDichVu)
        {
            tblDichVu dv = db.tblDichVus.Find(tblDichVu.ma_dv);
            if (ModelState.IsValid)//kiểm tra xem mô hình có hợp lệ cho cơ sở dữ liệu hay không 
            {
                String anh = dv.anh;
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);//Trả về tên tệp và phần mở rộng của chuỗi đường dẫn đã chỉ định.
                    String path = System.IO.Path.Combine(
                                           Server.MapPath("~/Content/Images/DichVu"), pic);//Kết hợp hai chuỗi thành một đường dẫn.
                    
                    file.SaveAs(path);
                    anh = "/Content/Images/DichVu/" + pic;
                    
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }

                dv.anh = anh;
                dv.don_vi = tblDichVu.don_vi;
                dv.gia = tblDichVu.gia;
                dv.ten_dv = tblDichVu.ten_dv;
                db.Entry(dv).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblDichVu);
        }

 
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDichVu tblDichVu = db.tblDichVus.Find(id);
            if (tblDichVu == null)
            {
                return HttpNotFound();
            }
            return View(tblDichVu);
        }
               
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken] //ngăn chặn các giả mạo yêu cầu trang web chéo
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                tblDichVu tblDichVu = db.tblDichVus.Find(id);
                db.tblDichVus.Remove(tblDichVu);
                db.SaveChanges();
            }
            catch
            {

            }
            return RedirectToAction("Index");
        }

        
    }
}

QLKS/Areas/Admin/Views/DichVu/Create.cshtml
@model QLKS.Models.tblDichVu

@{
    ViewBag.Title = "Thêm dịch vụ";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">@ViewBag.title</li>
</ol>

@using (Html.BeginForm("Create","DichVu", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Tên dịch vụ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ten_dv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ten_dv, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Giá", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control", type = "number" } })
            @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Đơn vị", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.don_vi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.don_vi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ton_kho, new { htmlAttributes = new { @class = "form-control", type = "number" } })
            @Html.ValidationMessageFor(model => model.ton_kho, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="file" class="form-control" style="width: 100%;" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" onclick="return check()" value="Thêm" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    function check() {
        var ten = $('#ten_dv').val();
        var gia = $('#gia').val();
        var soluong = $('#ton_kho').val();
        if (ten == '') {
            alert('Tên dịch vụ không được để trống !');
            return false;
        }
        if (gia == '') {
            alert('Giá tiền không được để trống !');
            return false;
        }
        if (soluong == '') {
            alert('Số lượng không được để trống !');
            return false;
        }
        return true;
    }
</script>

QLKS/Areas/Admin/Views/DichVu/Delete.cshtml
@model QLKS.Models.tblDichVu

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">@ViewBag.title</li>
</ol>

<h3>Bạn có chắc chắn muốn xóa ?</h3>
<div>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <img src="@Html.DisplayFor(model => model.anh)" style="width:100%;max-width:200px" />
            </div>
            <div class="col-md-5">
                <dl class="dl-horizontal">
                    <dt>
                        Tên dịch vụ
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ten_dv)
                    </dd>

                    <dt>
                        Giá
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.gia)
                    </dd>

                    <dt>
                        Đơn vị
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.don_vi)
                    </dd>

                </dl>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Delete" class="btn btn-danger" />
                }
            </div>
        </div>
    </div><hr/>
        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index")
        </div>
</div>

QLKS/Areas/Admin/Views/DichVu/Details.cshtml
@model QLKS.Models.tblDichVu

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblDichVu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ten_dv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ten_dv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.don_vi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.don_vi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ma_dv }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLKS/Areas/Admin/Views/DichVu/Edit.cshtml
@model QLKS.Models.tblDichVu

@{
    ViewBag.Title = "Sửa dịch vụ";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">@ViewBag.title</li>
</ol>

@using (Html.BeginForm("Edit", "DichVu", FormMethod.Post,
                                        new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ma_dv)

    <div class="form-group">
        @Html.Label("Tên dịch vụ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ten_dv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ten_dv, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Giá", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control", type = "number" } })
            @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Đơn vị", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.don_vi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.don_vi, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Tồn kho", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ton_kho, new { htmlAttributes = new { @class = "form-control", type = "number" } })
            @Html.ValidationMessageFor(model => model.ton_kho, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-8">
            <input type="file" name="file" id="file" class="form-control" style="width: 100%;" />
        </div>
        <div class="col-md-4">
            <img src="@Model.anh" width="200px" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" onclick="return check()" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}
<script>
    function check() {
        var ten = $('#ten_dv').val();
        var gia = $('#gia').val();
        var soluong = $('#ton_kho').val();
        if (ten == '') {
            alert('Tên dịch vụ không được để trống !');
            return false;
        }
        if (gia == '') {
            alert('Giá tiền không được để trống !');
            return false;
        }
        if (soluong == '') {
            alert('Số lượng không được để trống !');
            return false;
        }
        return true;
    }
</script>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QLKS/Areas/Admin/Views/DichVu/Index.cshtml
@model IEnumerable<QLKS.Models.tblDichVu>

@{
    ViewBag.Title = "Danh sách dịch vụ";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">Danh sách dịch vụ</li>
</ol>
<p>
    @Html.ActionLink("Thêm dịch vụ", "Create")
</p>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Danh sách dịch vụ
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th></th>
                        <th>
                            Tên dịch vụ
                        </th>
                        <th>
                            Giá
                        </th>
                        <th>
                            Tồn kho
                        </th>
                        <th>
                            Đơn vị
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            <img src="@Html.DisplayFor(modelItem => item.anh)" width="60px" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ten_dv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.gia)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ton_kho)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.don_vi)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ma_dv }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ma_dv })
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at @DateTime.Now</div>
</div>